### ISSUE TITLE
Second examples listed in TOC for docs for rack

### ISSUE THREAD

**Issue by kenperkins** [rackspace/rack#423] opened 2016-05-03 16:33 UTC
https://developer.rackspace.com/docs/rack-cli/services/#examples-for-services

In the left rail you can see a second set of examples listed:

![image](https://cloud.githubusercontent.com/assets/730664/14990598/2199d1e0-1112-11e6-97b0-c89edb6b8974.png)

@ktbartholomew could this be a deconst/template problem?

**Comment by ktbartholomew** [comment] 2016-05-03 17:12
It looks like the TOC's are duplicated in the source: https://raw.githubusercontent.com/rackspace/rack/master/docs/services/examples/index.rst

**Comment by jrperritt** [comment] 2016-05-03 17:25
@ktbartholomew But it was working up until today I think. I merged some changes but not there. It looks like you added those tocs a while back: https://github.com/rackspace/rack/blame/master/docs/services/examples/index.rst
I don't know anything about the formatting/syntax for these, but is the `:hidden` not being acknowledged?

**Comment by ktbartholomew** [comment] 2016-05-03 17:27
@smashwilson has been most active with the preparers lately, maybe he can weigh in on this.

**Comment by smashwilson** [comment] 2016-05-03 17:56
We just turned on the Strider build yesterday, so it wasn't being published automatically until then. Has anyone been manually submitting content in the interim? Otherwise, it's likely that the TOC changes from before have just now been published.

The preparer work I've been doing lately has mostly been in output formatting, writing assets and envelopes to disk instead of over the network. I wouldn't rule out preparer changes as a culprit but nothing jumps out at me right now.

What I'd _really_ like to do is revamp the way we generate TOCs in Sphinx entirely to not require the phony `_toc.rst` file at all. That's going to be difficult, though.

**Comment by jrperritt** [comment] 2016-05-03 18:37
I've been publishing the docs to production, but only for the `rack` releases.

**Comment by smashwilson** [comment] 2016-05-03 18:39
Ah, okay, good.

I'll double-check in the preparer... either way, not respecting `:hidden:` feels like a preparer bug to me.

**Comment by jrperritt** [comment] 2016-05-09 21:52
@smashwilson Were you able to determine if this is a bug in the preparer? If not (or if it isn't), I can look into ways of changing the docs to de-dupe the TOC. I'm not sure whether we need the `:hidden:` TOC there or not.

**Comment by smashwilson** [comment] 2016-05-09 23:30
Well, I'm rewriting the way that TOCs are generated entirely with deconst/preparer-sphinx#64. I haven't worked my way back to this specific case yet :wink:

But, I am guessing that the problem is the two `.. toctree` directives in [docs/services/index.rst](https://raw.githubusercontent.com/rackspace/rack/master/docs/services/index.rst). Try nixing the `:hidden:` one - the document structure will be preserved by the other two toctrees.

**Comment by jrperritt** [comment] 2016-05-10 00:09
>>  Try nixing the :hidden: one

Will do. With the ability to preview the docs in staging, I can safely just guess and check until I find something that works.

**Comment by jrperritt** [comment] 2016-05-10 15:15
by #437

**Comment by smashwilson** [comment] 2016-05-10 15:16
Excellent.

No idea why it was only rendering once before, though.

**Comment by jrperritt** [comment] 2016-05-10 15:19
>> No idea why it was only rendering once before, though.

Yeah, nor I. Oh well. Just another unsolved mystery...

**Closed** 2016-05-17 15:01 UTC
Labels: bug, Docs, done, reviewed
