### ISSUE TITLE
missing details in install doc for OSX and Linux

### ISSUE THREAD

**Issue by rose-coste** [rackspace/rack#313] opened 2015-09-01 14:41 UTC
At https://developer.rackspace.com/docs/rack-cli/configuration/#installation, under "OSX and Linux", three statements end with ":" rather than with whatever belongs on the other side of the colon

* After downloading the binary on OSX and Linux you will need to make the binary executable by typing:
* We also recommend you move or symbolically link it on these platforms to /usr/local/bin:
* You can now add it to your path with: 

@annegentle suggests that the missing detail here is
 chmod a+x /path/to/rack and then export PATH=$PATH:/usr/local/bin

I see this persistently on a Mac in both Firefox and Safari. In Opera and Chrome, I see black code-sample boxes flash by but they disappear quickly, leaving the same hanging colon.

**Comment by jnoller** [comment] 2015-09-01 15:13
This may be a ux problem with the new design @ktbartholomew as the content is in the docs. What URL Rose?

**Comment by rose-coste** [comment] 2015-09-01 15:15
https://developer.rackspace.com/docs/rack-cli/configuration/#installation

**Comment by ktbartholomew** [comment] 2015-09-01 15:19
Yep, working on it here: https://github.com/rackerlabs/nexus-control/issues/146

**Comment by ktbartholomew** [comment] 2015-09-01 15:28
I believe this is a dupe of https://github.com/rackerlabs/nexus-control/issues/146 which is now fixed, so this issue should be closed.

**Comment by jrperritt** [comment] 2015-09-01 17:10
This looks to be fixed on Chrome. Can someone else confirm?

**Comment by carolynvs** [comment] 2015-09-01 17:17
@jrperritt I see the instructions after the `:` now.

**Comment by jrperritt** [comment] 2015-09-01 17:18
Thank you @carolynvs . Closing.

**Closed by jrperritt** 2015-09-01 17:18 UTC
